version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: trading-prometheus
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: trading-grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus

  summary_exporter:
    build:
      context: .
      dockerfile: ./Dockerfile.exporter
    container_name: trading-summary-exporter
    restart: unless-stopped
    ports:
      - "9102:9102"
    environment:
      - ENV=testnet
    volumes:
      - ./reporting:/app/reporting
    depends_on:
      - prometheus

volumes:
  grafana-data: