gates:
  min_trades_rolling_30: ">= 30"
  min_avg_r_atr_30: ">= 0.2"
  expectancy_usd_30: "> 0"
  profit_factor_30: ">= 1.2"
  max_allowed_dd_pct: "<= 0.20"
  max_error_rate_pct: { threshold: "<= 1.0", severity: "warning" }
  max_fee_pct_of_pnl: "<= 0.5"
