name: Build & Publish Docker image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare registry credentials
        run: |
          echo "REGISTRY_USER=$(echo '${{ secrets.GHCR_USER }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "REGISTRY_TOKEN=${{ secrets.GHCR_TOKEN }}" >> $GITHUB_ENV

      - name: Log in to GHCR
        run: echo "$REGISTRY_TOKEN" | docker login ghcr.io -u "$REGISTRY_USER" --password-stdin

      - name: Build image
        run: docker build -t ghcr.io/$REGISTRY_USER/auto-trading-bot:${{ github.sha }} .

      - name: Push image with commit tag
        run: docker push ghcr.io/$REGISTRY_USER/auto-trading-bot:${{ github.sha }}

      - name: Tag & push latest
        run: |
          docker tag ghcr.io/$REGISTRY_USER/auto-trading-bot:${{ github.sha }} ghcr.io/$REGISTRY_USER/auto-trading-bot:latest
          docker push ghcr.io/$REGISTRY_USER/auto-trading-bot:latest

      - name: Deploy to droplet
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /opt/auto-trading-bot
            docker-compose pull
            docker-compose up -d
